service: test-circleci 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev${env:SLSUSER}

custom:
  stage: ${opt:stage, self:provider.stage}
  default-vars-stage: dev-user
  vars: ${file(./vars.yml):${opt:stage, self:custom.default-vars-stage}}

functions:
  hello:
    handler: handler.hello
    environment:
      MESSAGE: ${self:custom.vars.message}
    events:
      - http:
          path: hello
          method: get